/**
 * Sample receipts.
 *
 * Four cases a merchant actually meets, so the tool can be exercised without inventing data on
 * the spot. Each mirrors a scenario the testing protocol covers.
 */

import { NOT_SHOWN, type ClaimedReceipt } from './receipt.ts';

export interface Sample {
  id: string;
  title: string;
  blurb: string;
  claim: ClaimedReceipt;
}

export const SAMPLES: readonly Sample[] = [
  {
    id: 'genuine',
    title: 'A genuine receipt',
    blurb: 'Every field matches the ledger.',
    claim: {
      operationNumber: '23937025',
      amount: 1,
      recipientName: 'Sabina Don*',
      securityCode: '025',
    },
  },
  {
    id: 'forged-amount',
    title: 'A real payment, edited',
    blurb: 'A S/ 35 payment shared as S/ 350. The operation number is real — the amount is not.',
    claim: {
      operationNumber: '48120933',
      amount: 350,
      recipientName: 'Marisol Vent*',
      securityCode: '718',
    },
  },
  {
    id: 'fabricated',
    title: 'A payment that never happened',
    blurb: 'Generated by a fake-receipt app. The operation number exists nowhere.',
    claim: {
      operationNumber: '99180244',
      amount: 120,
      recipientName: 'Carlos Ram*',
      securityCode: '481',
    },
  },
  {
    id: 'unknown-code',
    title: "A receipt you can't fully read",
    blurb:
      'The security code was never mentioned in the public guidance, so the merchant does not know to look for it. A verdict is still reachable.',
    claim: {
      operationNumber: '60553281',
      amount: 240,
      recipientName: NOT_SHOWN,
      securityCode: NOT_SHOWN,
    },
  },
];
